apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scheduler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scheduler.labels" . | nindent 8 }}
    spec:
      {{- with .Values.scheduler.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: db-test-cluster
        image: alpine:latest
        command: ["sh", "-c",{{ include "mysql.initContainerCommand" . | quote }}]
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.scheduler.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: scheduler
          securityContext:
            {{- toYaml .Values.scheduler.securityContext | nindent 12 }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          ports:
            - name: scheduler
              containerPort: {{ .Values.scheduler.service.ports.scheduler.containerPort }}
              protocol: {{ .Values.scheduler.service.ports.scheduler.protocol }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          env:
            - name: MONGODB_HOST
              value: {{ include "db.fullname" . | quote }}
            - name: HELM_MICROSERVICE
              value: {{ include "helm.fullname" . | quote }}
            - name: HELM_MICROSERVICE_PORT
              value: {{ .Values.helm.service.ports.helm.port | quote}}
            {{- with .Values.scheduler.prediction.mysql.envVars }}
            - name: MYSQL_USER
              value: {{ .user | quote }} 
            - name: MYSQL_PASSWORD
              value: {{ .password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .data | quote }}
            {{- end }}
            - name: MYSQL_HOST
              value: {{ include "mysql.fullname" . }}
            - name: MYSQL_PORT
              value: {{ .Values.scheduler.prediction.mysql.service.ports.mysql.containerPort | quote }}
