apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - name: scheduler
      port: {{ .Values.scheduler.service.ports.scheduler.port }}
      targetPort: {{ .Values.scheduler.service.ports.scheduler.targetPort }}
      protocol: {{ .Values.scheduler.service.ports.scheduler.protocol }}
      {{- if and (or (eq .Values.scheduler.service.type "NodePort") (eq .Values.scheduler.service.type "LoadBalancer")) (not (empty .Values.scheduler.service.ports.scheduler.nodePort)) }}
      nodePort: {{ .Values.scheduler.service.ports.scheduler.nodePort }}
      {{- end }}
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}
