apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vernemq.labels" . | nindent 8 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vernemq.labels" . | nindent 8 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
---
# Source: vernemq/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vernemq.labels" . | nindent 8 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vernemq.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "vernemq.fullname" . }}
  apiGroup: rbac.authorization.k8s.io