apiVersion: v1
kind: Secret
metadata:
  name: vernemq-tls-secret
data:
  ca.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVWlJqZzdDKy9Q
    MGh3ejN3UFk3UFltSlNMbVJnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURUxNQWtHQTFVRUJoTUNV
    MUF4RERBS0JnTlZCQWdNQTFaTVF6RVJNQThHQTFVRUJ3d0lWbUZzWlc1agphV0V4RFRBTEJnTlZC
    QU1NQkUxcFEwRXdIaGNOTWpRd01USTFNVEl4TmpVMldoY05NelF3TVRJeU1USXhOalUyCldqQTlN
    UXN3Q1FZRFZRUUdFd0pUVURFTU1Bb0dBMVVFQ0F3RFZreERNUkV3RHdZRFZRUUhEQWhXWVd4bGJt
    TnAKWVRFTk1Bc0dBMVVFQXd3RVRXbERRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFE
    Q0NBUW9DZ2dFQgpBTTJEb0Fja04vRThrSkJTaEo4TE1ESVptV1d0NElhY2s0a2VMcjRVVitOL21w
    VEp1Y1IvZWZVc1pxZC9hai9HCkd4YUU3R3NYMFhYV1pCUVNkSGZDQkZ5UGlVbFoxTFFGTmpDd2FI
    cWpwNDFCU1VXeGMvK3VDUzd1dzVGYTFmVmsKMllpcjhMa2hDcUFreExaQUZMK3plWHVIdGdFMkRY
    RHVhRlhkWExQOTQyUWFtUHMydzNkYmNzc2lKMXJsbjJxcAppci9kSnN4aGdvN2ZrYUtRMjNZb2gw
    dE8vakJqTmVMN1ZYRkluTGtLOUsxT1hiNnRFZEhSVEVpRURLZE1la1FkCkRyb2xCT0RNcEtHL0hi
    cGJabmIxOTc3OGxZNG51dHhVQlNzOXIyalJvL2p6ajZoMVJDVTJsN1ZtcEtIcFIzRUcKQUJQS3E1
    Qml3bnJCQWNnT1IyeXBRbU1DQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkx2blhFUWMxdVZzR3hB
    NQo2Z2xPd29jYUJmd1dNQjhHQTFVZEl3UVlNQmFBRkx2blhFUWMxdVZzR3hBNTZnbE93b2NhQmZ3
    V01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjVJaXNq
    V1A3bndCM0g4OHNVNW5UNC8KaVhYOWRDSXpQQ2QwbDJ1RG5CRnIxWHd3c3hYM2QxYzVtL3BhdHJn
    azFGRTlMNE56RXpmeDd1dkJDeDk3UVgzSwpnWkpEUlk0NjBRdkl5SnBRRU1YTkxGVXpFRE1JdHBK
    Z2JwWUw3M3o2bGtvYk8rempxcGgzaHc3dXI5eXJjNFdNCjh5QmtQWU54b2FzYzBVeWNSNHdZMzFp
    RXhndEVEZkZkTUdJVTB5TWd2THRVY2syRVU0NnhNME1TdksrN2JCNkIKYnFza3BUZ3ZrQTM2ZFlS
    eUR0bTNPOFRRS0hVbWkrNzcrMUtTTVE2UHNTNzJ6dE5ldkF4WUM4Ukd5M2xmbnZLTQpFN3oyWVU2
    VE5jbXFJKzdLdEFMMUNKY0pzQzUybXVJcW5tTUtvdzRWL3pUYk14ZzRaWmNwNmRjZ29rbjZhNWM9
    Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls_key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktvd2dnU21BZ0VBQW9JQkFRRHQydVh3YTZTR0tvWmcKdHdpMGh3WUIyQzYrMnFFOStlTU4x
    N2UwOHV1OWFrVWk0T0VZdlBHaGFENGlFTm43OGRCTzNFTHo0YXI5cDgzawphTm1jZUhWaDlvdU53
    QXZ1MlVuWXl1NTJVc1kvM0p5QnBBRUUzcGxFaWYwQmpRbUgwQUxiaTgzRXlxelJvN3AyCllUckMz
    VlBiaStqYjJweXZoNTk3bFY0QmtpRUNXc1JSSmsxYi9tTmFPVlVyNzVQZ1RMMG9hQjFmVmVON1U4
    dm4KdUNOY3dDeU4yMXVoNmN4TWs5NUdnaVp5Rzk0cS9ZK01ISVg4QjdxOUdxSDVSUUxqMkNYUzhu
    WktVSFFNWG83MQpmaStnaFZyQ2pydTlPOTZXVlBmbWRvdUdBWCtyaTAzem1NdVlHcUN0anhvOUND
    OFNFZ04yNThZeXFpRVVVam01CndHYTBXYS9oQWdNQkFBRUNnZ0VCQUlQRFBKZm4rWmM5WFgyY1I1
    MUNJMGpJU25UOXhrNy83QkVTRERtWVRKRjgKbWxvTSs0VnB2ZTF0UXVZNk1aZUpTSjAzRlh2bTZv
    Tmovd0htTjQ2ZmlGOUJaZU9ibk1DdTdHTEZZRDU1OGtzVQpXanJTOEtHUzhwTHVZaE1HMzEyMkZL
    OHNqa3ZTL3RPUGdNN3RZOURwTFBnMVZFVGVvT2Y0R0pnc2tZd0xPSEFGCmFLM1lVa0JCOHYyTWNY
    N0tjYkdUZzRzNXBueW5zcHVBd2hBQjB0NzdDTThKbTJJQnZ6VUtneDZIOEhYS2ZPMFAKSHpTMmtj
    MlJDQ2NCUnlsOEY4UHZhcFQyb1lWS0Nrb1lYTGxUaENBYUUyeEJJbWhDN1BUa2pFNkNTS3hJczRC
    Vgpvd3Fmc0I2SGUrWTdCNFA0ZVNWSXUyMlJ5bVFYY2dEVVVxVXdIY1lEbXNFQ2dZRUEvcHBJQ1NY
    dUwydXB4OUl6Ckd4bzlsaTZQcTk0cW5lZUNKVTdaazZyZFdXaGFRdXJmd2FpRCtKQStWY3h5bzNx
    Qnp4YnpqTUJjVHNSeE1ITEMKTHRJQzhGUndOQlBqSm15QnQwdnhOMGNVQ2gvNnpqTFgrWFBnVXV4
    RUJDK3o1RWwyRkdxa2czbFc1eVpOMGk4MAo4enVrNS9sNG1Qdmw0enNIVTZ5QVhQWjExYWtDZ1lF
    QTd5a1dHVGpScDh2bWMvTXBEV3FaK01OYnNVdlJLdUwyCkFPOFVpbGdoT3h5RWxZRjlmZjBhQ3dq
    Wm9yUEpDanhPQUNrd3J5TG1PYUdmc0xOSkUyN2VDbW9vTlpBaGExb2kKVmNBRHYweW9OcGVQUnNC
    eGxJbm81L0djbUJaUS9qNDdscTZHblJMVVVoUm5IU1Y3aVBlYWtBTUJ3UFIvdXRVWQpQc3YweGFH
    eisza0NnWUVBMkROaklJR1pOYU9UVlIvbVRnbUdhdFczSXhkUjBTMGFrMXZWMzFPbEM1dFZxcVdR
    CnhQNjRzb2FxcUdrb29ESVRzU3VvUGNuTG1RZXZwcGlNMVAxNWlXUHF0QTUvUWMyNmlWQnYwYVVH
    RzJMMHM4engKSWQrSWltSWZqLzZDSUVWUmhCemEvdG8zTmFxTlF3TGJVQUZDRThzQTRjaG1ld05S
    UVhpbXVFcUIzYUVDZ1lFQQo0MUdXSTVzU0MvK09xQjh6b2dEMUlMSHZjWEd5K3FTSFZ4UG4zaWN1
    VHRVb1lFS1lXU3c5bU1kc3RXMVZaVmswCmVvcXNMNHRvY05iaXhqMWk5QW1wR3hVVDZ2VjREbVc1
    eE8raG9DN29wQnNpb0FsQzdBQzVVOTBmRHFBSGsrRHIKR3FvQVlVUUljNHZaQnFjZDZHNFFoMW1V
    VFNjWVVTbEN4azF0OW50Z2EyRUNnWUVBckdGNndGOHdBY0NiZUw3RApGckk0aVlBV2RIWGZuRlF1
    SGtUU0d3NFJXTFZkMHVHWVVLVDlzUUowVkR6MTQ0dnNIaVhrc1ZrRmtFeWhRdTJBCmxxWHZwajFG
    cEozeit1aWFhbDVLaG1hOElaaklIMGFPc0RZNGh5QzVnOFd6cGRGMW5BTXZpaWRWY1FuWDJjR2kK
    Z0ZGSmh6UkViRXpXaFhYTSswZHQ5S2liL3QwPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  tls.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZRQ0ZEWnptVEZ4V1hwaFNncit2
    anZOODFKMHZQc2NNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1EMHgKQ3pBSkJnTlZCQVlUQWxOUU1Rd3dD
    Z1lEVlFRSURBTldURU14RVRBUEJnTlZCQWNNQ0ZaaGJHVnVZMmxoTVEwdwpDd1lEVlFRRERBUk5h
    VU5CTUI0WERUSTBNREV5TlRFeU1qYzBNMW9YRFRNME1ERXlNakV5TWpjME0xb3dTREVMCk1Ba0dB
    MVVFQmhNQ1UxQXhEREFLQmdOVkJBZ01BMVpNUXpFUk1BOEdBMVVFQnd3SVZtRnNaVzVqYVdFeEdE
    QVcKQmdOVkJBTU1EM1psY201bGJYRXRjMlZ5ZG1salpUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJR
    QURnZ0VQQURDQwpBUW9DZ2dFQkFPM2E1ZkJycElZcWhtQzNDTFNIQmdIWUxyN2FvVDM1NHczWHQ3
    VHk2NzFxUlNMZzRSaTg4YUZvClBpSVEyZnZ4MEU3Y1F2UGhxdjJuemVSbzJaeDRkV0gyaTQzQUMr
    N1pTZGpLN25aU3hqL2NuSUdrQVFUZW1VU0oKL1FHTkNZZlFBdHVMemNUS3JOR2p1blpoT3NMZFU5
    dUw2TnZhbksrSG4zdVZYZ0dTSVFKYXhGRW1UVnYrWTFvNQpWU3Z2aytCTXZTaG9IVjlWNDN0VHkr
    ZTRJMXpBTEkzYlc2SHB6RXlUM2thQ0puSWIzaXI5ajR3Y2hmd0h1cjBhCm9mbEZBdVBZSmRMeWRr
    cFFkQXhlanZWK0w2Q0ZXc0tPdTcwNzNwWlU5K1oyaTRZQmY2dUxUZk9ZeTVnYW9LMlAKR2owSUx4
    SVNBM2JueGpLcUlSUlNPYm5BWnJSWnIrRUNBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFF
    QQp4KzRHUFB3UGdKU2F1Uk54NjNyWjZLeUZpUUJKSk5sdEZsM1NPdVh5SmtZTG1Ea0tPQ2FRNDBG
    cXYwcm8rR1FICnNjYlo1Qms4c2dTSS94Ym5lL1VINFl1YzJEckZvVjg2UmVLSGx0ZW5MUFlEMmty
    elBHQkpJS0NYeWNXdVpZT0UKMTlhZCtwV2x1S0FsR0o4bGRxWmRnZmZXZ0NyTXNQNnJ0Y0kwNDh2
    OXlnSml6SHZ2dFpwOUpKK3h3ZUJNR2hONApRZkQyNmJKeG1FZmQzdmRSakxiQWYva0JwZHJ6ZUZK
    UUxYRjdSQzJwcEwzdnMwb0RpVU5QS0FlZzBONkM1Q0xVCktBeUdVVmpKYUdONFNPaTJOTkllNk5K
    dkZlV2l5cVhTcDRhZGVsQkl6RFJtU1MrSHovUXBOanpnZHZ0Qkw4TnQKOTg1dXd4U25SYk42c0JL
    MWRWakhHdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
