apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vernemq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- if .Values.vernemq.service.ports.mqtt.enabled }}
    - name: mqtt
      port: {{ .Values.vernemq.service.ports.mqtt.port }}
      targetPort: {{ .Values.vernemq.service.ports.mqtt.targetPort }}
      protocol: {{ .Values.vernemq.service.ports.mqtt.protocol }}
    {{- end }}
    {{- if .Values.vernemq.service.ports.mqtts.enabled }}
    - name: mqtts
      port: {{ .Values.vernemq.service.ports.mqtts.port }}
      targetPort: {{ .Values.vernemq.service.ports.mqtts.targetPort }}
      protocol: {{ .Values.vernemq.service.ports.mqtts.protocol }}
    {{- end }}
    {{- if .Values.vernemq.service.ports.ws.enabled }}
    - name: ws
      port: {{ .Values.vernemq.service.ports.ws.port }}
      targetPort: {{ .Values.vernemq.service.ports.ws.targetPort }}
      protocol: {{ .Values.vernemq.service.ports.ws.protocol }}
    {{- end }}
    {{- if .Values.vernemq.service.ports.wss.enabled }}
    - name: wss
      port: {{ .Values.vernemq.service.ports.wss.port }}
      targetPort: {{ .Values.vernemq.service.ports.wss.targetPort }}
      protocol: {{ .Values.vernemq.service.ports.wss.protocol }}
    {{- end }}
    {{- if .Values.vernemq.service.ports.prometheus.enabled }}
    - name: prometheus
      port: {{ .Values.vernemq.service.ports.prometheus.port }}
      targetPort: {{ .Values.vernemq.service.ports.prometheus.targetPort }}
      protocol: {{ .Values.vernemq.service.ports.prometheus.protocol }}
    {{- end }}
  selector:
    {{- include "vernemq.selectorLabels" . | nindent 4 }}
