apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.ports.postgresql.port }}
      targetPort: {{ .Values.postgresql.service.ports.postgresql.targetPort }}
      protocol: {{ .Values.postgresql.service.ports.postgresql.protocol }}
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}