apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.globalService }}
    {{- include "globalServiceAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.kafka.service.ports.kafka.port }}
      targetPort: {{ .Values.kafka.service.ports.kafka.targetPort }}
      protocol: {{ .Values.kafka.service.ports.kafka.protocol }}
      {{- if and (or (eq .Values.kafka.service.type "NodePort") (eq .Values.kafka.service.type "LoadBalancer")) (not (empty .Values.kafka.service.ports.kafka.nodePort)) }}
      nodePort: {{ .Values.kafka.service.ports.kafka.nodePort }}
      {{- end }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
