apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kafka.fullname" . }}-headless
  {{- if not .Values.kafka.autoscaling.enabled }}
  replicas: {{ .Values.kafka.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka.labels" . | nindent 8 }}
    spec:
      {{- with .Values.kafka.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.kafka.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.kafka.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafka.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.kafka.podSecurityContext | nindent 8 }}
      containers:
        - name: kafka
          securityContext:
            {{- toYaml .Values.kafka.securityContext | nindent 12 }}
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - name: kafka
              containerPort: {{ .Values.kafka.service.ports.kafka.containerPort }}
              protocol: {{ .Values.kafka.service.ports.kafka.protocol }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ include "zookeeper.uri" . | quote }}
            - name: KAFKA_LISTENERS
              value: {{ include "kafka.listeners" . | quote }}
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ include "kafka.advertisedlisteners" . | quote }}
          {{- with .Values.kafka.envVars }}
            - name: KAFKA_BROKER_ID
              value: {{ .kafkaBrokerId | quote }}
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ .kafkaAdvertisedHost | quote }}
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: {{ .kafkaInterBrokerListenerName | quote }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .KafkaListenerSecurityProtocolMap | quote }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: {{ .kafkaAutoCreateTopicsEnabler | quote }}
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .kafkaOffsetsTopicReplicationFactor | quote }}
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
          {{- end }}
          volumeMounts:
            {{- if .Values.kafka.persistence.enabled }}
            - name: kafka-data
              mountPath: /var/lib/kafka/data
            - name: kafka-logs
              mountPath: /kafka/kafka-logs
            {{- end }}
      volumes:
  {{- if and .Values.kafka.persistence.enabled .Values.kafka.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.kafka.persistence.existingClaim $ }}
  {{- else if not .Values.kafka.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
        {{- range .Values.kafka.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size | quote }}
    - metadata:
        name: kafka-logs
      spec:
        accessModes:
        {{- range .Values.kafka.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size | quote }}
  {{- end }}
