apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kongatrial
  annotations:
    konghq.com/strip-path: "true"
    # konghq.com/rewrite-target: /konga/register
spec:
  ingressClassName: kong
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: openapi-konga
            port:
              number: 1337
      - path: /konga
        pathType: ImplementationSpecific
        backend:
          service:
            name: openapi-konga
            port:
              number: 1337
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - host: 
    http:
      paths:
      - path: /frontend
        pathType: ImplementationSpecific
        backend:
          service:
            name: openapi-frontend
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - host: 
    http:
      paths:
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: openapi-backend
            port:
              number: 8999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - host: 
    http:
      paths:
      - path: /keycloak
        pathType: ImplementationSpecific
        backend:
          service:
            name: s21-idm-keycloak-keycloak
            port:
              number: 8080
