apiVersion: v1
kind: ServiceAccount
metadata:
  name: asdo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: asdo-cluster
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - pods/log
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: asdo-cluster
  namespace: asdo
subjects:
  - kind: ServiceAccount
    name: asdo
    namespace: asdo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: asdo-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asdo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: asdo
    namespace: asdo