apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "zookeeper.fullname" . }}-headless
  {{- if not .Values.zookeeper.autoscaling.enabled }}
  replicas: {{ .Values.zookeeper.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zookeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zookeeper.labels" . | nindent 8 }}
    spec:
      {{- with .Values.zookeeper.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.zookeeper.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.zookeeper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zookeeper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.zookeeper.podSecurityContext | nindent 8 }}
      containers:
        - name: zookeeper
          securityContext:
            {{- toYaml .Values.zookeeper.securityContext | nindent 12 }}
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - name: zookeeper
              containerPort: {{ .Values.zookeeper.service.ports.zookeeper.containerPort }}
              protocol: {{ .Values.zookeeper.service.ports.zookeeper.protocol }}
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.zookeeper.persistence.enabled }}
            - name: zookeeper-data
              mountPath: /data
            - name: zookeeper-log
              mountPath: /datalog
            {{- end }}
      volumes:
  {{- if and .Values.zookeeper.persistence.enabled .Values.zookeeper.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.zookeeper.persistence.existingClaim $ }}
  {{- else if not .Values.zookeeper.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
        {{- range .Values.zookeeper.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.zookeeper.persistence.size | quote }}
    - metadata:
        name: zookeeper-log
      spec:
        accessModes:
        {{- range .Values.zookeeper.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.zookeeper.persistence.size | quote }}
  {{- end }}
