apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.backend.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.containerPort }}
              protocol: {{ .Values.backend.service.protocol }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: deckKongAddr
              value: {{ include "kong.fullname" . }}-admin:8444
            - name: keycloakClient
              value: {{ .Values.backend.envVars.keycloakClient | quote }}
            - name: keycloakClientSecret
              value: {{ .Values.backend.envVars.keycloakClientSecret | quote }}
            - name: keycloakRealm
              value: {{ .Values.backend.envVars.keycloakRealm | quote }}
            - name: keycloakUrl
              value: {{ .Values.backend.envVars.keycloakUrl | quote }}
            - name: kongAddr
              value: {{ include "kong.fullname" . }}-proxy:80
            - name: portalDomain
              value: {{ include "backend.fullname" . }}:8999
