apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "minio.fullname" . }}-headless
  {{- if not .Values.minio.autoscaling.enabled }}
  replicas: {{ .Values.minio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio.labels" . | nindent 8 }}
    spec:
      {{- with .Values.minio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.minio.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.minio.podSecurityContext | nindent 8 }}
      containers:
        - name: minio
          securityContext:
            {{- toYaml .Values.minio.securityContext | nindent 12 }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args: ["minio", "server", "data"]
          ports:
            - containerPort: {{ .Values.minio.service.containerPort }}
              protocol: {{ .Values.minio.service.protocol }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          {{- with .Values.minio.envVars }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .minioUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .minioPassword | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.minio.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size | quote }}
