apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.globalService }}
    {{- include "globalServiceAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: api
      port: {{ .Values.api.service.ports.api.port }}
      targetPort: {{ .Values.api.service.ports.api.targetPort }}
      protocol: {{ .Values.api.service.ports.api.protocol }}
      {{- if and (or (eq .Values.api.service.type "NodePort") (eq .Values.api.service.type "LoadBalancer")) (not (empty .Values.api.service.ports.api.nodePort)) }}
      nodePort: {{ .Values.api.service.ports.api.nodePort }}
      {{- end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
